---
title: "Eurostat"
output: html_notebook
---
Pasos:
1. Carga de datos y eliminación de columnas raras, sin datos.
2. Eliminamos campo SEX de tabla Trabajo para poder unir las dos tablas
3. Renombramos campo INDIC
4. Unimos tablas con rbind en df
5. Convertimos valores ":" en NA's
6. Seleccionamos paises interesantes eu+otros
7. Hacemos dos nuevas tablas (spread) a partir de df, una por paises y otra por INDIC
#Led

```{r}
library(magrittr)
edu <- read.csv2("dat/edu.csv",sep="")
trabajo <- read.csv2("dat/trabajo.csv",sep="")

tb.edu<-as.data.frame(table(edu$INDIC_ED))
tb.tra<-as.data.frame(table(trabajo$INDIC_EM))

colnames(edu)
edu<-edu[,-c(1,3,5,7,9)]
colnames(trabajo)
trabajo<-trabajo[,-c(1,3,5,7,9,11)]

trabajo %<>% dplyr::filter(SEX=="Total") %>% 
  dplyr::select(c(1,2,4,5)) %>% 
  dplyr::rename(INDIC=INDIC_EM)

edu %<>% dplyr::rename(INDIC=INDIC_ED)

df <- rbind(edu,trabajo)

df$Value<-as.numeric(as.character(df$Value))
df$Value[df$Value == ":"] <- NA

summary(df$Value)
str(df$Value)

table(df$GEO)
paises_eu = c("Austria","Belgium","Bulgaria","Croatia","Cyprus","Czech Republic","Denmark ","Estonia","Finland","France","Germany (until 1990 former territory of the FRG)","Greece","Hungary","Ireland","Italy","Latvia","Lithuania","Luxembourg","Malta","Netherlands","Poland","Portugal","Romania","Slovakia","Slovenia","Spain","Sweden","United Kingdom","Japan","United States","Switzerland")
df <- df %>% dplyr::filter(GEO==paises_eu)
droplevels(df)

df_geo<-df %>% tidyr::spread(GEO, Value)
df_indic<-df %>% tidyr::spread(INDIC, Value)




```

# Import data
```{r}

```

